import streamlit as st
import pandas as pd

# Simulated data (replace this with your dataset or model for better predictions)
data = [
    {"id": 1, "text": "I've been drinking every night just to forget my problems. I can't stop thinking about it.", "addiction_type": "substance_abuse", "confidence": 0.95},
    {"id": 2, "text": "I just spent my entire paycheck on online gambling. I know I should stop, but I can't help myself.", "addiction_type": "gambling", "confidence": 0.92},
    {"id": 3, "text": "I feel like I need to check my social media every few minutes, or I get anxious.", "addiction_type": "digital_addiction", "confidence": 0.90},
    {"id": 4, "text": "Whenever I feel stressed, I turn to alcohol. It’s the only way I can cope.", "addiction_type": "substance_abuse", "confidence": 0.97},
    {"id": 5, "text": "I can't stop playing this game. It's taking over my life, and I ignore everything else.", "addiction_type": "digital_addiction", "confidence": 0.93},
    {"id": 6, "text": "I've lost so much money on gambling sites. I tell myself it's my last time, but I always go back.", "addiction_type": "gambling", "confidence": 0.94},
    {"id": 7, "text": "I used to be social, but now I only feel comfortable with a drink in my hand.", "addiction_type": "substance_abuse", "confidence": 0.89},
    {"id": 8, "text": "My friends say I spend too much time online. I just can’t stop scrolling through videos.", "addiction_type": "digital_addiction", "confidence": 0.85},
    {"id": 9, "text": "I feel like I can’t control my betting habits. It’s affecting my relationships.", "addiction_type": "gambling", "confidence": 0.96},
    {"id": 10, "text": "I find myself buying drugs even when I can't afford it. It’s like I have no control.", "addiction_type": "substance_abuse", "confidence": 0.99},
    {"id": 11, "text": "Every time I think about quitting smoking, I just light another cigarette.", "addiction_type": "substance_abuse", "confidence": 0.91},
    {"id": 12, "text": "I lost my job because I was spending too much time gambling online.", "addiction_type": "gambling", "confidence": 0.93},
    {"id": 13, "text": "I check my notifications even when I'm in the middle of a conversation.", "addiction_type": "digital_addiction", "confidence": 0.90},
    {"id": 14, "text": "I can’t function without my morning coffee, and I drink way too much of it.", "addiction_type": "substance_abuse", "confidence": 0.87},
    {"id": 15, "text": "I feel really guilty after spending all my money on betting.", "addiction_type": "gambling", "confidence": 0.92},
    {"id": 16, "text": "I always find myself binge-watching series for hours. I lose track of time.", "addiction_type": "digital_addiction", "confidence": 0.88},
    {"id": 17, "text": "I keep telling myself I'll quit drinking, but I always end up at the bar.", "addiction_type": "substance_abuse", "confidence": 0.94},
    {"id": 18, "text": "I spend most of my paycheck on poker games. It's getting out of hand.", "addiction_type": "gambling", "confidence": 0.91},
    {"id": 19, "text": "I feel anxious if I can't use my phone for a few minutes.", "addiction_type": "digital_addiction", "confidence": 0.93},
    {"id": 20, "text": "I often drink to celebrate and then regret it the next day.", "addiction_type": "substance_abuse", "confidence": 0.89},
    {"id": 21, "text": "I bet on games without thinking about the consequences.", "addiction_type": "gambling", "confidence": 0.95},
    {"id": 22, "text": "I can't stop playing this mobile game, even when I have work to do.", "addiction_type": "digital_addiction", "confidence": 0.90},
    {"id": 23, "text": "I feel like I can't enjoy life without a drink in my hand.", "addiction_type": "substance_abuse", "confidence": 0.93},
    {"id": 24, "text": "I try to avoid my gambling friends, but I still end up joining them.", "addiction_type": "gambling", "confidence": 0.88},
    {"id": 25, "text": "I find myself mindlessly scrolling through my feed for hours.", "addiction_type": "digital_addiction", "confidence": 0.91},
    {"id": 26, "text": "I think about using drugs every day, and it's affecting my mental health.", "addiction_type": "substance_abuse", "confidence": 0.96},
    {"id": 27, "text": "I promised myself I'd stop betting, but then I place another wager.", "addiction_type": "gambling", "confidence": 0.94},
    {"id": 28, "text": "I can't go a day without checking my social media, or I feel lost.", "addiction_type": "digital_addiction", "confidence": 0.89},
    {"id": 29, "text": "I hide my drinking from my family, but it’s becoming impossible to manage.", "addiction_type": "substance_abuse", "confidence": 0.95},
    {"id": 30, "text": "I gamble to escape reality, but it only makes things worse.", "addiction_type": "gambling", "confidence": 0.97},
    {"id": 31, "text": "I get anxious when I’m not connected to the internet.", "addiction_type": "digital_addiction", "confidence": 0.90},
    {"id": 32, "text": "I drink to socialize, but I often end up drinking alone.", "addiction_type": "substance_abuse", "confidence": 0.94},
    {"id": 33, "text": "I regret every gambling loss, but I can’t stop myself.", "addiction_type": "gambling", "confidence": 0.96},
    {"id": 34, "text": "I feel lost without my favorite online games; they’re my escape.", "addiction_type": "digital_addiction", "confidence": 0.92},
    {"id": 35, "text": "I always think I can control my drinking, but it gets the best of me.", "addiction_type": "substance_abuse", "confidence": 0.93},
    {"id": 36, "text": "I lie about how much I gamble to my friends and family.", "addiction_type": "gambling", "confidence": 0.88},
    {"id": 37, "text": "I check my phone before I even get out of bed in the morning.", "addiction_type": "digital_addiction", "confidence": 0.91},
    {"id": 38, "text": "I binge-drink every weekend, but I don't think I have a problem.", "addiction_type": "substance_abuse", "confidence": 0.94},
    {"id": 39, "text": "Every time I get money, I think about how I can use it for gambling.", "addiction_type": "gambling", "confidence": 0.95},
    {"id": 40, "text": "I feel a rush when I post something online and get likes instantly.", "addiction_type": "digital_addiction", "confidence": 0.90},
    {"id": 41, "text": "I drink to feel better about my life, but it just makes it worse.", "addiction_type": "substance_abuse", "confidence": 0.96},
    {"id": 42, "text": "I find it hard to resist the urge to gamble when I see ads online.", "addiction_type": "gambling", "confidence": 0.93},
    {"id": 43, "text": "I can’t focus on anything else when I’m gaming; it’s all-consuming.", "addiction_type": "digital_addiction", "confidence": 0.94},
    {"id": 44, "text": "I’ve tried to quit drinking multiple times, but I always relapse.", "addiction_type": "substance_abuse", "confidence": 0.95},
    {"id": 45, "text": "Gambling has cost me friendships and family relationships.", "addiction_type": "gambling", "confidence": 0.98},
    {"id": 46, "text": "I feel like I’m missing out if I’m not online all the time.", "addiction_type": "digital_addiction", "confidence": 0.89},
    {"id": 47, "text": "I can't stop buying drugs, even when I know it's ruining my life.", "addiction_type": "substance_abuse", "confidence": 0.99},
    {"id": 48, "text": "I gamble even when I'm supposed to be saving money for bills.", "addiction_type": "gambling", "confidence": 0.96},
    {"id": 49, "text": "My screen time is way too high, but I just can’t stop using my devices.", "addiction_type": "digital_addiction", "confidence": 0.94},
    {"id": 50, "text": "I often black out from drinking, and I don’t remember what happened.", "addiction_type": "substance_abuse", "confidence": 0.99},
    {"id": 51, "text": "I sometimes drink a little too much, but I think it's normal.", "addiction_type": "substance_abuse", "confidence": 0.65},
    {"id": 52, "text": "I enjoy playing games, but it doesn't take up all my time.", "addiction_type": "digital_addiction", "confidence": 0.70},
    {"id": 53, "text": "I play the lottery occasionally, but I don't spend much on it.", "addiction_type": "gambling", "confidence": 0.60},
    {"id": 54, "text": "I drink socially, but sometimes I go overboard.", "addiction_type": "substance_abuse", "confidence": 0.75},
    {"id": 55, "text": "I find myself checking my phone more than I used to.", "addiction_type": "digital_addiction", "confidence": 0.72},
    {"id": 56, "text": "I bet on sports once in a while, but it's just for fun.", "addiction_type": "gambling", "confidence": 0.55},
    {"id": 57, "text": "I think about having a drink at the end of the day, but I don’t always do it.", "addiction_type": "substance_abuse", "confidence": 0.68},
    {"id": 58, "text": "I enjoy browsing social media, but it doesn’t interfere with my life.", "addiction_type": "digital_addiction", "confidence": 0.67},
    {"id": 59, "text": "I sometimes gamble when I’m feeling lucky, but it's not a big deal.", "addiction_type": "gambling", "confidence": 0.60},
    {"id": 60, "text": "I feel fine when I skip a few days without drinking.", "addiction_type": "substance_abuse", "confidence": 0.50},
    {"id": 61, "text": "I use my phone a lot, but I can put it down when I need to.", "addiction_type": "digital_addiction", "confidence": 0.64},
    {"id": 62, "text": "Gambling is just a hobby for me; I don’t take it too seriously.", "addiction_type": "gambling", "confidence": 0.58},
    {"id": 63, "text": "I drink wine occasionally and don’t feel bad about it.", "addiction_type": "substance_abuse", "confidence": 0.62},
    {"id": 64, "text": "I play video games to unwind, but I make time for other activities.", "addiction_type": "digital_addiction", "confidence": 0.66},
    {"id": 65, "text": "I sometimes bet on horse races, but only for fun.", "addiction_type": "gambling", "confidence": 0.57},
    {"id": 66, "text": "I enjoy a few beers on the weekends; it’s not a problem for me.", "addiction_type": "substance_abuse", "confidence": 0.60},
    {"id": 67, "text": "I scroll through social media during my breaks, but I don't feel addicted.", "addiction_type": "digital_addiction", "confidence": 0.63},
    {"id": 68, "text": "I buy scratch-off tickets sometimes, but it's not a big part of my life.", "addiction_type": "gambling", "confidence": 0.55},
    {"id": 69, "text": "I drink a cocktail every now and then, and I don’t feel guilty about it.", "addiction_type": "substance_abuse", "confidence": 0.72},
    {"id": 70, "text": "I enjoy gaming but I also have a job and social life.", "addiction_type": "digital_addiction", "confidence": 0.65},
    {"id": 71, "text": "I have a bet with friends occasionally, but it’s all in good fun.", "addiction_type": "gambling", "confidence": 0.54},
    {"id": 72, "text": "I only drink when I go out, which is not too often.", "addiction_type": "substance_abuse", "confidence": 0.70},
    {"id": 73, "text": "I find it easy to log off my games when I need to.", "addiction_type": "digital_addiction", "confidence": 0.66},
    {"id": 74, "text": "Gambling is just a way to pass time for me, nothing serious.", "addiction_type": "gambling", "confidence": 0.59},
    {"id": 75, "text": "I occasionally drink with friends but I can stop whenever I want.", "addiction_type": "substance_abuse", "confidence": 0.65},
    {"id": 76, "text": "I enjoy watching streams online, but it’s not the only thing I do.", "addiction_type": "digital_addiction", "confidence": 0.62},
    {"id": 77, "text": "I sometimes feel tempted to gamble, but I resist most of the time.", "addiction_type": "gambling", "confidence": 0.61},
    {"id": 78, "text": "I drink sometimes, but I don’t think it’s a problem for me.", "addiction_type": "substance_abuse", "confidence": 0.58},
    {"id": 79, "text": "I watch videos for entertainment, but I don't think about it much.", "addiction_type": "digital_addiction", "confidence": 0.60},
    {"id": 80, "text": "I’ve placed a few bets, but I don’t consider myself a gambler.", "addiction_type": "gambling", "confidence": 0.57},
    {"id": 81, "text": "I enjoy a drink after work, but it’s nothing I can't handle.", "addiction_type": "substance_abuse", "confidence": 0.66},
    {"id": 82, "text": "I play games occasionally, but they don’t consume my life.", "addiction_type": "digital_addiction", "confidence": 0.63},
    {"id": 83, "text": "I don’t bet often, just when I’m with friends.", "addiction_type": "gambling", "confidence": 0.55},
    {"id": 84, "text": "I have a drink every few weeks; it feels fine to me.", "addiction_type": "substance_abuse", "confidence": 0.62},
    {"id": 85, "text": "I enjoy online quizzes, but I don’t do them every day.", "addiction_type": "digital_addiction", "confidence": 0.64},
    {"id": 86, "text": "I sometimes think about gambling, but I rarely act on it.", "addiction_type": "gambling", "confidence": 0.56},
    {"id": 87, "text": "I have a drink with dinner occasionally, but that’s it.", "addiction_type": "substance_abuse", "confidence": 0.65},
    {"id": 88, "text": "I can quit using my phone anytime, it’s just a habit.", "addiction_type": "digital_addiction", "confidence": 0.59},
    {"id": 89, "text": "I might place a small bet, but I don’t worry about it.", "addiction_type": "gambling", "confidence": 0.54},
    {"id": 90, "text": "I enjoy having a beer at parties, but it’s not a necessity.", "addiction_type": "substance_abuse", "confidence": 0.67},
    {"id": 91, "text": "I like to watch TV series, but I can go without it easily.", "addiction_type": "digital_addiction", "confidence": 0.62},
    {"id": 92, "text": "I might gamble a little when I’m bored, but it’s rare.", "addiction_type": "gambling", "confidence": 0.58},
    {"id": 93, "text": "I drink every now and then, but it’s not often enough to worry.", "addiction_type": "substance_abuse", "confidence": 0.65},
    {"id": 94, "text": "I scroll through Instagram occasionally but have other interests.", "addiction_type": "digital_addiction", "confidence": 0.61},
    {"id": 95, "text": "I might place a bet or two when I'm out, but nothing major.", "addiction_type": "gambling", "confidence": 0.53},
    {"id": 96, "text": "I enjoy a drink during special occasions, nothing too crazy.", "addiction_type": "substance_abuse", "confidence": 0.64},
    {"id": 97, "text": "I sometimes spend time gaming, but I also exercise regularly.", "addiction_type": "digital_addiction", "confidence": 0.60},
    {"id": 98, "text": "I have placed a bet on a whim, but it doesn’t happen often.", "addiction_type": "gambling", "confidence": 0.52},
    {"id": 99, "text": "I drink socially, and I feel in control of it.", "addiction_type": "substance_abuse", "confidence": 0.66},
    {"id": 100, "text": "I spend time online, but I prioritize my responsibilities first.", "addiction_type": "digital_addiction", "confidence": 0.62},
     {"id": 101, "text": "I occasionally have a glass of wine with dinner, but it's rare.", "addiction_type": "none", "confidence": 0.20},
    {"id": 102, "text": "I use my phone to check the weather and then put it down.", "addiction_type": "none", "confidence": 0.15},
    {"id": 103, "text": "I enjoy playing board games with friends on the weekends.", "addiction_type": "none", "confidence": 0.10},
    {"id": 104, "text": "I drink coffee in the morning, but I don’t rely on it.", "addiction_type": "none", "confidence": 0.25},
    {"id": 105, "text": "I might watch a movie occasionally, but I don’t binge.", "addiction_type": "none", "confidence": 0.30},
    {"id": 106, "text": "I only go to the casino for special events; I don't gamble regularly.", "addiction_type": "none", "confidence": 0.20},
    {"id": 107, "text": "I try new recipes occasionally, but cooking isn’t an obsession.", "addiction_type": "none", "confidence": 0.15},
    {"id": 108, "text": "I use social media to stay in touch with family, but not excessively.", "addiction_type": "none", "confidence": 0.25},
    {"id": 109, "text": "I enjoy reading books, but I also spend time outdoors.", "addiction_type": "none", "confidence": 0.10},
    {"id": 110, "text": "I sometimes have dessert after dinner, but not every day.", "addiction_type": "none", "confidence": 0.20},
    {"id": 111, "text": "I like to walk my dog daily, but I don't feel tied to it.", "addiction_type": "none", "confidence": 0.15},
    {"id": 112, "text": "I go to the gym a few times a week, but I also enjoy rest days.", "addiction_type": "none", "confidence": 0.25},
    {"id": 113, "text": "I like to binge-watch a series sometimes, but I can stop easily.", "addiction_type": "none", "confidence": 0.30},
    {"id": 114, "text": "I occasionally try a new drink, but I'm not a big drinker.", "addiction_type": "none", "confidence": 0.20},
    {"id": 115, "text": "I enjoy gardening, but it’s a hobby, not an obsession.", "addiction_type": "none", "confidence": 0.10},
    {"id": 116, "text": "I listen to music while working, but I can focus without it.", "addiction_type": "none", "confidence": 0.25},
    {"id": 117, "text": "I might scroll through my phone while waiting, but I don’t need it.", "addiction_type": "none", "confidence": 0.20},
    {"id": 118, "text": "I drink tea in the evenings, but it’s just a calming ritual.", "addiction_type": "none", "confidence": 0.15},
    {"id": 119, "text": "I enjoy visiting friends occasionally, but I don’t feel lonely without it.", "addiction_type": "none", "confidence": 0.10},
    {"id": 120, "text": "I watch a few shows during the week, but I don’t feel compelled to binge.", "addiction_type": "none", "confidence": 0.30},
    {"id": 121, "text": "I might play a mobile game while waiting, but I can easily put it down.", "addiction_type": "none", "confidence": 0.20},
    {"id": 122, "text": "I enjoy a drink with friends occasionally; it’s not a habit.", "addiction_type": "none", "confidence": 0.25},
    {"id": 123, "text": "I read the news online, but I don’t spend too much time on it.", "addiction_type": "none", "confidence": 0.15},
    {"id": 124, "text": "I do some puzzles for fun, but they don’t take up all my time.", "addiction_type": "none", "confidence": 0.10},
    {"id": 125, "text": "I enjoy drawing occasionally, but it’s not something I have to do.", "addiction_type": "none", "confidence": 0.20},
    {"id": 126, "text": "I play sports for fun, but I don’t feel pressured to win.", "addiction_type": "none", "confidence": 0.15},
    {"id": 127, "text": "I might have a beer while watching a game, but it’s not frequent.", "addiction_type": "none", "confidence": 0.25},
    {"id": 128, "text": "I only shop online when I need something, not just for fun.", "addiction_type": "none", "confidence": 0.20},
    {"id": 129, "text": "I watch educational videos online, but not every day.", "addiction_type": "none", "confidence": 0.15},
    {"id": 130, "text": "I like to try new foods when I go out, but I don’t have cravings for them.", "addiction_type": "none", "confidence": 0.10},
    {"id": 131, "text": "I take walks for exercise, but I can skip it if needed.", "addiction_type": "none", "confidence": 0.25},
    {"id": 132, "text": "I might play an online game with friends once in a while.", "addiction_type": "none", "confidence": 0.30},
    {"id": 133, "text": "I enjoy cooking for fun, but it’s not something I feel I must do.", "addiction_type": "none", "confidence": 0.20},
    {"id": 134, "text": "I read a book occasionally, but it’s not every night.", "addiction_type": "none", "confidence": 0.15},
    {"id": 135, "text": "I occasionally check my email, but I can wait to respond.", "addiction_type": "none", "confidence": 0.20},
    {"id": 136, "text": "I play a few rounds of golf during the summer; it’s just a leisure activity.", "addiction_type": "none", "confidence": 0.10},
    {"id": 137, "text": "I might snack while watching TV, but it’s not something I rely on.", "addiction_type": "none", "confidence": 0.25},
    {"id": 138, "text": "I enjoy taking photos on vacation, but I don’t need to do it daily.", "addiction_type": "none", "confidence": 0.15},
    {"id": 139, "text": "I might scroll through Pinterest for ideas, but it’s not addictive.", "addiction_type": "none", "confidence": 0.20},
    {"id": 140, "text": "I only attend a bar for special occasions; I don't go often.", "addiction_type": "none", "confidence": 0.25},
    {"id": 141, "text": "I cook dinner a few times a week, but I don’t feel obligated to.", "addiction_type": "none", "confidence": 0.10},
    {"id": 142, "text": "I look for new recipes online, but it’s just for fun.", "addiction_type": "none", "confidence": 0.15},
    {"id": 143, "text": "I sometimes watch documentaries, but not every week.", "addiction_type": "none", "confidence": 0.20},
    {"id": 144, "text": "I enjoy a drink during special events, but I can take it or leave it.", "addiction_type": "none", "confidence": 0.30},
    {"id": 145, "text": "I read reviews before trying a new restaurant, but it doesn’t consume me.", "addiction_type": "none", "confidence": 0.25},
    {"id": 146, "text": "I occasionally play with my kids, but I also encourage them to play outside.", "addiction_type": "none", "confidence": 0.15},
    {"id": 147, "text": "I might do some gardening when I have time; it’s relaxing.", "addiction_type": "none", "confidence": 0.10},
    {"id": 148, "text": "I occasionally visit a friend’s house for dinner; it’s nice to catch up.", "addiction_type": "none", "confidence": 0.20},
    {"id": 149, "text": "I like to watch the news occasionally but I’m not obsessed with it.", "addiction_type": "none", "confidence": 0.15},
    {"id": 150, "text": "I go for a walk in the park sometimes, but it’s not a daily routine.", "addiction_type": "none", "confidence": 0.20},
     {"id": 151, "text": "I occasionally enjoy a drink with dinner, but it's not a habit.", "addiction_type": "none", "confidence": 0.18},
    {"id": 152, "text": "I like to watch a movie now and then, but I can easily skip it.", "addiction_type": "none", "confidence": 0.22},
    {"id": 153, "text": "I read a book when I have free time, but it's not my main activity.", "addiction_type": "none", "confidence": 0.17},
    {"id": 154, "text": "I sometimes play games with friends, but it's infrequent.", "addiction_type": "none", "confidence": 0.20},
    {"id": 155, "text": "I might check my social media once a day, but I don't dwell on it.", "addiction_type": "none", "confidence": 0.21},
    {"id": 156, "text": "I enjoy cooking new recipes occasionally, but I don't feel pressured to.", "addiction_type": "none", "confidence": 0.15},
    {"id": 157, "text": "I like to visit the gym when I can, but I don't obsess over it.", "addiction_type": "none", "confidence": 0.20},
    {"id": 158, "text": "I enjoy gardening occasionally, but I also have other hobbies.", "addiction_type": "none", "confidence": 0.19},
    {"id": 159, "text": "I might have a snack while watching TV, but I don't do it every time.", "addiction_type": "none", "confidence": 0.16},
    {"id": 160, "text": "I go for a run when I feel like it, but it's not a strict routine.", "addiction_type": "none", "confidence": 0.22},
    {"id": 161, "text": "I enjoy a glass of water when I'm thirsty, but I don’t crave it.", "addiction_type": "none", "confidence": 0.14},
    {"id": 162, "text": "I check my email when I need to, but I don’t feel compelled to.", "addiction_type": "none", "confidence": 0.23},
    {"id": 163, "text": "I might go for ice cream on a hot day, but it's a rare treat.", "addiction_type": "none", "confidence": 0.18},
    {"id": 164, "text": "I take my dog for a walk when I can, but it’s not a daily obligation.", "addiction_type": "none", "confidence": 0.20},
    {"id": 165, "text": "I occasionally try new restaurants, but I don't feel the need to go out often.", "addiction_type": "none", "confidence": 0.21},
    {"id": 166, "text": "I might attend a concert if it's convenient, but I don't seek them out.", "addiction_type": "none", "confidence": 0.17},
    {"id": 167, "text": "I enjoy photography as a hobby, but I don’t feel I must do it all the time.", "addiction_type": "none", "confidence": 0.15},
    {"id": 168, "text": "I only play video games occasionally, and I can stop anytime.", "addiction_type": "none", "confidence": 0.19},
    {"id": 169, "text": "I drink herbal tea in the evenings sometimes, but I don’t rely on it.", "addiction_type": "none", "confidence": 0.20},
    {"id": 170, "text": "I enjoy reading the news occasionally, but it doesn’t consume my time.", "addiction_type": "none", "confidence": 0.16},
    {"id": 171, "text": "I like to go out for walks in nature, but it’s not a frequent activity.", "addiction_type": "none", "confidence": 0.23},
    {"id": 172, "text": "I enjoy baking, but I don’t feel pressured to do it often.", "addiction_type": "none", "confidence": 0.19},
    {"id": 173, "text": "I might do yoga once in a while, but it’s not a routine.", "addiction_type": "none", "confidence": 0.20},
    {"id": 174, "text": "I enjoy casual dining out, but I don’t do it frequently.", "addiction_type": "none", "confidence": 0.22},
    {"id": 175, "text": "I check my messages when I want to, but I don't obsess over it.", "addiction_type": "none", "confidence": 0.21},
    {"id": 176, "text": "I might attend a local event now and then, but it’s not a priority.", "addiction_type": "none", "confidence": 0.18},
    {"id": 177, "text": "I enjoy a good book now and then, but I don't feel the need to read daily.", "addiction_type": "none", "confidence": 0.20},
    {"id": 178, "text": "I like to watch documentaries occasionally, but it’s not a habit.", "addiction_type": "none", "confidence": 0.22},
    {"id": 179, "text": "I might use a fitness app sometimes, but I don’t feel dependent on it.", "addiction_type": "none", "confidence": 0.16},
    {"id": 180, "text": "I might enjoy some cake during a celebration, but I don't crave sweets daily.", "addiction_type": "none", "confidence": 0.19},
    {"id": 181, "text": "I check the weather app occasionally, but I don't rely on it every day.", "addiction_type": "none", "confidence": 0.15},
    {"id": 182, "text": "I enjoy spending time with family, but I also value my alone time.", "addiction_type": "none", "confidence": 0.20},
    {"id": 183, "text": "I listen to podcasts occasionally, but I don’t have to every day.", "addiction_type": "none", "confidence": 0.22},
    {"id": 184, "text": "I sometimes engage in arts and crafts, but it’s not an obsession.", "addiction_type": "none", "confidence": 0.20},
    {"id": 185, "text": "I enjoy swimming in the summer, but I don't go often.", "addiction_type": "none", "confidence": 0.18},
    {"id": 186, "text": "I might attend a workshop if it interests me, but I don’t feel pressured to.", "addiction_type": "none", "confidence": 0.21},
    {"id": 187, "text": "I enjoy trying new foods during vacations, but it’s not a requirement.", "addiction_type": "none", "confidence": 0.19},
    {"id": 188, "text": "I sometimes visit museums, but it’s not a regular activity for me.", "addiction_type": "none", "confidence": 0.20},
    {"id": 189, "text": "I might go to the park occasionally, but I can skip it without issue.", "addiction_type": "none", "confidence": 0.15},
    {"id": 190, "text": "I enjoy learning new skills, but I don't feel addicted to it.", "addiction_type": "none", "confidence": 0.18},
    {"id": 191, "text": "I find myself drinking every weekend, even when I plan not to.", "addiction_type": "substance_abuse", "confidence": 0.85},
    {"id": 192, "text": "I gamble frequently, often losing track of time and money.", "addiction_type": "gambling", "confidence": 0.90},
    {"id": 193, "text": "I spend hours scrolling through social media, even when I have other tasks.", "addiction_type": "digital_addiction", "confidence": 0.88},
    {"id": 194, "text": "I feel anxious if I can't check my phone for updates.", "addiction_type": "digital_addiction", "confidence": 0.92},
    {"id": 195, "text": "I often drink to cope with stress, and I can't remember the last time I didn't.", "addiction_type": "substance_abuse", "confidence": 0.87},
    {"id": 196, "text": "I place bets even when I know I shouldn’t, hoping to win back losses.", "addiction_type": "gambling", "confidence": 0.85},
    {"id": 197, "text": "I feel compelled to check my gaming stats multiple times a day.", "addiction_type": "digital_addiction", "confidence": 0.89},
    {"id": 198, "text": "I can't seem to stop binge-watching series, even when I have responsibilities.", "addiction_type": "digital_addiction", "confidence": 0.86},
    {"id": 199, "text": "I frequently find myself drinking alone, especially on tough days.", "addiction_type": "substance_abuse", "confidence": 0.84},
    {"id": 200, "text": "I often make excuses to gamble more, telling myself it will pay off.", "addiction_type": "gambling", "confidence": 0.88},
    {"id": 201, "text": "I can’t resist the urge to check my social media first thing in the morning.", "addiction_type": "digital_addiction", "confidence": 0.91},
    {"id": 202, "text": "I rely on alcohol to relax, even in social situations.", "addiction_type": "substance_abuse", "confidence": 0.86},
    {"id": 203, "text": "I often find myself borrowing money to gamble.", "addiction_type": "gambling", "confidence": 0.89},
    {"id": 204, "text": "I lose track of time while playing video games and neglect my chores.", "addiction_type": "digital_addiction", "confidence": 0.87},
    {"id": 205, "text": "I drink more than I intend when I'm out with friends.", "addiction_type": "substance_abuse", "confidence": 0.82},
    {"id": 206, "text": "I frequently check gambling websites even when I’ve promised to stop.", "addiction_type": "gambling", "confidence": 0.91},
    {"id": 207, "text": "I feel a rush when I check for new likes or messages online.", "addiction_type": "digital_addiction", "confidence": 0.88},
    {"id": 208, "text": "I often think about my next drink, even while at work.", "addiction_type": "substance_abuse", "confidence": 0.84},
    {"id": 209, "text": "I have gone into debt due to my gambling habits.", "addiction_type": "gambling", "confidence": 0.90},
    {"id": 210, "text": "I struggle to stop playing video games, even when I want to.", "addiction_type": "digital_addiction", "confidence": 0.89},
    {"id": 211, "text": "I often feel guilty about how much I drink.", "addiction_type": "substance_abuse", "confidence": 0.83},
    {"id": 212, "text": "I find myself chasing losses when I gamble, thinking I can win it back.", "addiction_type": "gambling", "confidence": 0.86},
    {"id": 213, "text": "I feel restless when I’m not online for an extended period.", "addiction_type": "digital_addiction", "confidence": 0.90},
    {"id": 214, "text": "I use alcohol as a way to escape my problems.", "addiction_type": "substance_abuse", "confidence": 0.87},
    {"id": 215, "text": "I often gamble despite knowing the odds are against me.", "addiction_type": "gambling", "confidence": 0.84},
    {"id": 216, "text": "I feel like I can't function without checking my phone regularly.", "addiction_type": "digital_addiction", "confidence": 0.92},
    {"id": 217, "text": "I sometimes black out from drinking and can't remember the night.", "addiction_type": "substance_abuse", "confidence": 0.89},
    {"id": 218, "text": "I frequently argue with friends about my gambling habits.", "addiction_type": "gambling", "confidence": 0.85},
    {"id": 219, "text": "I prioritize gaming over spending time with family.", "addiction_type": "digital_addiction", "confidence": 0.88},
    {"id": 220, "text": "I often lie about how much I drink to others.", "addiction_type": "substance_abuse", "confidence": 0.86},
    {"id": 221, "text": "I gamble to feel excitement, even when I can't afford to lose.", "addiction_type": "gambling", "confidence": 0.90},
    {"id": 222, "text": "I feel compelled to post updates on social media, even when I’m busy.", "addiction_type": "digital_addiction", "confidence": 0.91},
    {"id": 223, "text": "I often drink to cope with feelings of loneliness.", "addiction_type": "substance_abuse", "confidence": 0.88},
    {"id": 224, "text": "I often place bets when I’m stressed, thinking it will help me relax.", "addiction_type": "gambling", "confidence": 0.87},
    {"id": 225, "text": "I can't resist the urge to check my favorite online game multiple times a day.", "addiction_type": "digital_addiction", "confidence": 0.89},
    {"id": 226, "text": "I find myself drinking even when I don't enjoy it anymore.", "addiction_type": "substance_abuse", "confidence": 0.85},
    {"id": 227, "text": "I often gamble in secret, hiding it from my friends and family.", "addiction_type": "gambling", "confidence": 0.92},
    {"id": 228, "text": "I feel like I need to be online to feel connected.", "addiction_type": "digital_addiction", "confidence": 0.90},
    {"id": 229, "text": "I frequently choose drinking over spending time with my loved ones.", "addiction_type": "substance_abuse", "confidence": 0.87},
    {"id": 230, "text": "I often say I will stop gambling, but I can’t seem to do it.", "addiction_type": "gambling", "confidence": 0.89},
    {"id": 231, "text": "I often neglect my hobbies in favor of spending time online.", "addiction_type": "digital_addiction", "confidence": 0.88},
    {"id": 232, "text": "I might buy gadgets I don't need during sales.", "addiction_type": "none", "confidence": 0.24},
    {"id": 233, "text": "I need multiple coffees throughout the day to function.", "addiction_type": "substance_abuse", "confidence": 0.82},
    {"id": 234, "text": "I might stay up late reading, but I can stop if needed.", "addiction_type": "none", "confidence": 0.19},
    {"id": 235, "text": "I spend hours scrolling TikTok without realizing it.", "addiction_type": "digital_addiction", "confidence": 0.86},
    {"id": 236, "text": "I find myself looking for excuses to drink socially.", "addiction_type": "substance_abuse", "confidence": 0.83},
    {"id": 237, "text": "I feel compelled to keep betting even after losing large sums.", "addiction_type": "gambling", "confidence": 0.88},
    {"id": 238, "text": "I spend weekends gaming instead of socializing.", "addiction_type": "digital_addiction", "confidence": 0.84},
    {"id": 239, "text": "I enjoy movie marathons occasionally, but I don’t do it often.", "addiction_type": "none", "confidence": 0.21},
    {"id": 240, "text": "I often skip meals while gaming for hours.", "addiction_type": "digital_addiction", "confidence": 0.88},
    {"id": 241, "text": "I find it hard to start the day without checking Instagram.", "addiction_type": "digital_addiction", "confidence": 0.85},
    {"id": 242, "text": "I use alcohol to unwind even when not stressed.", "addiction_type": "substance_abuse", "confidence": 0.81},
    {"id": 243, "text": "I often participate in online challenges just to keep up.", "addiction_type": "digital_addiction", "confidence": 0.79},
    {"id": 244, "text": "I occasionally place small bets, but it doesn't affect me much.", "addiction_type": "none", "confidence": 0.23},
    {"id": 245, "text": "I check my phone every few minutes without realizing it.", "addiction_type": "digital_addiction", "confidence": 0.86},
    {"id": 246, "text": "I gamble with friends on weekends, hoping to win big.", "addiction_type": "gambling", "confidence": 0.83},
    {"id": 247, "text": "I snack unconsciously while watching TV for hours.", "addiction_type": "substance_abuse", "confidence": 0.78},
    {"id": 248, "text": "I feel uneasy when I don't receive enough likes on my posts.", "addiction_type": "digital_addiction", "confidence": 0.82},
    {"id": 249, "text": "I play video games late into the night, even on workdays.", "addiction_type": "digital_addiction", "confidence": 0.87},
    {"id": 250, "text": "I don't drink often, but when I do, I binge heavily.", "addiction_type": "substance_abuse", "confidence": 0.85},
    {"id": 251, "text": "I spend money impulsively on gambling apps.", "addiction_type": "gambling", "confidence": 0.89},
    {"id": 252, "text": "I try to cut back on caffeine, but I always relapse.", "addiction_type": "substance_abuse", "confidence": 0.77},
    {"id": 253, "text": "I enjoy outdoor activities, but I'm not addicted to them.", "addiction_type": "none", "confidence": 0.18},
    {"id": 254, "text": "I get frustrated when I can't access Wi-Fi or data.", "addiction_type": "digital_addiction", "confidence": 0.80},
    {"id": 255, "text": "I drink energy drinks daily to stay alert.", "addiction_type": "substance_abuse", "confidence": 0.84},
    {"id": 256, "text": "I scroll through online stores even when I don’t plan to buy anything.", "addiction_type": "digital_addiction", "confidence": 0.81},
    {"id": 257, "text": "I avoid attending events without alcohol.", "addiction_type": "substance_abuse", "confidence": 0.82},
    {"id": 258, "text": "I can't resist betting when there's a big sports match.", "addiction_type": "gambling", "confidence": 0.86},
    {"id": 259, "text": "I enjoy listening to music, but I can live without it.", "addiction_type": "none", "confidence": 0.22},
    {"id": 260, "text": "I lose track of time scrolling through memes.", "addiction_type": "digital_addiction", "confidence": 0.79},
    {"id": 261, "text": "I need coffee every morning, no matter what.", "addiction_type": "substance_abuse", "confidence": 0.83},
    {"id": 262, "text": "I can’t start my day without a strong cup of coffee.", "addiction_type": "substance_abuse", "confidence": 0.85},
    {"id": 263, "text": "I need to smoke a cigarette after every meal.", "addiction_type": "substance_abuse", "confidence": 0.79},
    {"id": 264, "text": "I crave chocolate every afternoon.", "addiction_type": "substance_abuse", "confidence": 0.76},
    {"id": 265, "text": "I can't resist binge-watching TV shows every weekend.", "addiction_type": "behavioral_addiction", "confidence": 0.82},
    {"id": 266, "text": "I feel the need to check my phone every few minutes.", "addiction_type": "behavioral_addiction", "confidence": 0.88},
    {"id": 267, "text": "I often find myself scrolling through social media for hours.", "addiction_type": "behavioral_addiction", "confidence": 0.90},
    {"id": 268, "text": "I need to play video games daily to feel satisfied.", "addiction_type": "behavioral_addiction", "confidence": 0.84},
    {"id": 269, "text": "I can't go a day without my morning tea.", "addiction_type": "substance_abuse", "confidence": 0.80},
    {"id": 270, "text": "I have to buy new clothes every month.", "addiction_type": "behavioral_addiction", "confidence": 0.77},
    {"id": 271, "text": "I need to drink energy drinks to keep going throughout the day.", "addiction_type": "substance_abuse", "confidence": 0.81},
    {"id": 272, "text": "I rely on caffeine to get through my workday.", "addiction_type": "substance_abuse", "confidence": 0.87},
    {"id": 273, "text": "I can't help but eat junk food every night.", "addiction_type": "substance_abuse", "confidence": 0.78},
    {"id": 274, "text": "I feel anxious if I don't have my phone on me.", "addiction_type": "behavioral_addiction", "confidence": 0.83},
    {"id": 275, "text": "I often find myself shopping online instead of doing chores.", "addiction_type": "behavioral_addiction", "confidence": 0.80},
    {"id": 276, "text": "I need to drink wine to unwind after a stressful day.", "addiction_type": "substance_abuse", "confidence": 0.75},
    {"id": 277, "text": "I can't focus without listening to music.", "addiction_type": "behavioral_addiction", "confidence": 0.76},
    {"id": 278, "text": "I need my daily dose of social media likes to feel validated.", "addiction_type": "behavioral_addiction", "confidence": 0.85},
    {"id": 279, "text": "I often lose track of time while browsing the internet.", "addiction_type": "behavioral_addiction", "confidence": 0.82},
    {"id": 280, "text": "I can't go to bed without watching at least one episode of a show.", "addiction_type": "behavioral_addiction", "confidence": 0.78},
    {"id": 281, "text": "I feel the need to drink soda every day.", "addiction_type": "substance_abuse", "confidence": 0.73},
    {"id": 282, "text": "I have to play poker every week with friends.", "addiction_type": "behavioral_addiction", "confidence": 0.74},
    {"id": 283, "text": "I need to check my email constantly.", "addiction_type": "behavioral_addiction", "confidence": 0.76},
    {"id": 284, "text": "I can’t resist eating dessert every night.", "addiction_type": "substance_abuse", "confidence": 0.80},
    {"id": 285, "text": "I often spend hours on TikTok.", "addiction_type": "behavioral_addiction", "confidence": 0.89},
    {"id": 286, "text": "I need to smoke weed to relax.", "addiction_type": "substance_abuse", "confidence": 0.79},
    {"id": 287, "text": "I feel compelled to play video games even when I have work to do.", "addiction_type": "behavioral_addiction", "confidence": 0.88},
    {"id": 288, "text": "I can't resist buying new tech gadgets.", "addiction_type": "behavioral_addiction", "confidence": 0.77},
    {"id": 289, "text": "I drink alcohol every weekend to socialize.", "addiction_type": "substance_abuse", "confidence": 0.82},
    {"id": 290, "text": "I need to check news updates multiple times a day.", "addiction_type": "behavioral_addiction", "confidence": 0.81},
    {"id": 291, "text": "I can't go to sleep without reading.", "addiction_type": "behavioral_addiction", "confidence": 0.76},
    {"id": 292, "text": "I have to play fantasy sports every season.", "addiction_type": "behavioral_addiction", "confidence": 0.74},
    {"id": 293, "text": "I often find myself eating snacks when I'm bored.", "addiction_type": "substance_abuse", "confidence": 0.78},
    {"id": 294, "text": "I feel the need to log my meals every day.", "addiction_type": "behavioral_addiction", "confidence": 0.75},
    {"id": 295, "text": "I can’t resist scrolling through dating apps.", "addiction_type": "behavioral_addiction", "confidence": 0.83},
    {"id": 296, "text": "I need to buy something new to feel happy.", "addiction_type": "behavioral_addiction", "confidence": 0.81},
    {"id": 297, "text": "I can’t go without my morning smoothie.", "addiction_type": "substance_abuse", "confidence": 0.76},
    {"id": 298, "text": "I often binge on chips while watching movies.", "addiction_type": "substance_abuse", "confidence": 0.79},
    {"id": 299, "text": "I need to take a break from work to scroll through social media.", "addiction_type": "behavioral_addiction", "confidence": 0.82},
    {"id": 300, "text": "I find it hard to resist sweets when they are around.", "addiction_type": "substance_abuse", "confidence": 0.77},
    {"id": 301, "text": "I need to play mobile games during my commute.", "addiction_type": "behavioral_addiction", "confidence": 0.80},
    {"id": 302, "text": "I can't go a day without using my computer.", "addiction_type": "behavioral_addiction", "confidence": 0.84},
    {"id": 303, "text": "I often feel the urge to shop online at night.", "addiction_type": "behavioral_addiction", "confidence": 0.78},{"id": 304, "text": "I enjoy watching movies on weekends but don't do it often.", "addiction_type": "none", "confidence": 0.35},
    {"id": 305, "text": "I occasionally play video games, but it's not a regular habit.", "addiction_type": "none", "confidence": 0.40},
    {"id": 306, "text": "I read books from time to time, but I don't feel the need to read every day.", "addiction_type": "none", "confidence": 0.25},
    {"id": 307, "text": "I sometimes scroll through social media, but it doesn't consume my time.", "addiction_type": "none", "confidence": 0.32},
    {"id": 308, "text": "I enjoy cooking on weekends, but I don't consider it an obsession.", "addiction_type": "none", "confidence": 0.30},
    {"id": 309, "text": "I watch documentaries occasionally, but I don't binge-watch.", "addiction_type": "none", "confidence": 0.29},
    {"id": 310, "text": "I like to go for walks, but I don’t feel the need to do it every day.", "addiction_type": "none", "confidence": 0.31},
    {"id": 311, "text": "I occasionally listen to music, but I can go days without it.", "addiction_type": "none", "confidence": 0.34},
    {"id": 312, "text": "I enjoy casual shopping but don't have a compulsive urge to buy things.", "addiction_type": "none", "confidence": 0.30},
    {"id": 313, "text": "I like to try new recipes sometimes, but it’s not a daily thing.", "addiction_type": "none", "confidence": 0.28},
    {"id": 314, "text": "I go to the gym occasionally, but I don’t feel pressured to go every day.", "addiction_type": "none", "confidence": 0.36},
    {"id": 315, "text": "I enjoy gardening, but I don’t spend all my free time on it.", "addiction_type": "none", "confidence": 0.33},
    {"id": 316, "text": "I watch sports games when they are on, but it's not a regular habit.", "addiction_type": "none", "confidence": 0.30},
    {"id": 317, "text": "I enjoy going to cafes with friends occasionally, but it's not frequent.", "addiction_type": "none", "confidence": 0.29},
    {"id": 318, "text": "I like to go hiking during the summer, but I don’t do it all the time.", "addiction_type": "none", "confidence": 0.31},
    {"id": 319, "text": "I occasionally do puzzles, but it’s just for fun, not a habit.", "addiction_type": "none", "confidence": 0.25},
    {"id": 320, "text": "I enjoy casual conversations with friends but don’t feel the need to be social all the time.", "addiction_type": "none", "confidence": 0.30},
    {"id": 321, "text": "I sometimes try out new hobbies, but I don’t stick with them long-term.", "addiction_type": "none", "confidence": 0.28},
    {"id": 322, "text": "I like to attend local events occasionally, but it's not a regular occurrence.", "addiction_type": "none", "confidence": 0.34},
    {"id": 323, "text": "I sometimes binge on snacks during movie nights, but it's rare.", "addiction_type": "none", "confidence": 0.32},
    {"id": 324, "text": "I like to read news articles but don’t obsessively check the news.", "addiction_type": "none", "confidence": 0.30},
    {"id": 325, "text": "I enjoy going out to eat, but I can also cook at home and be satisfied.", "addiction_type": "none", "confidence": 0.36},
    {"id": 326, "text": "I dabble in painting when I feel inspired, but I don’t do it frequently.", "addiction_type": "none", "confidence": 0.29},
    {"id": 327, "text": "I like to catch up on podcasts occasionally but don’t listen daily.", "addiction_type": "none", "confidence": 0.35},
    {"id": 328, "text": "I enjoy playing board games with friends but don’t seek them out regularly.", "addiction_type": "none", "confidence": 0.33},
    {"id": 329, "text": "I sometimes spend time with family on weekends but have my own space too.", "addiction_type": "none", "confidence": 0.31},
    {"id": 330, "text": "I occasionally indulge in spa days, but I don’t feel compelled to do it often.", "addiction_type": "none", "confidence": 0.30},
    {"id": 331, "text": "I like to try new teas but can also stick to my favorites.", "addiction_type": "none", "confidence": 0.27},
    {"id": 332, "text": "I sometimes take pictures during outings but don’t overdo it.", "addiction_type": "none", "confidence": 0.32},
    {"id": 333, "text": "I enjoy browsing through bookstores occasionally but don’t buy books every time.", "addiction_type": "none", "confidence": 0.34},
    {"id": 334, "text": "I like to do yoga a few times a month but can skip it without any guilt.", "addiction_type": "none", "confidence": 0.30},
    {"id": 335, "text": "I enjoy learning new skills but don’t feel the need to master them all.", "addiction_type": "none", "confidence": 0.29},
    {"id": 336, "text": "I like to watch the occasional live music show but not every week.", "addiction_type": "none", "confidence": 0.35},
    {"id": 337, "text": "I sometimes do karaoke with friends but don’t seek it out often.", "addiction_type": "none", "confidence": 0.30},
    {"id": 338, "text": "I occasionally enjoy craft projects but don’t make them a priority.", "addiction_type": "none", "confidence": 0.28},
    {"id": 339, "text": "I like to go on road trips but can be content staying home too.", "addiction_type": "none", "confidence": 0.31},
    {"id": 340, "text": "I sometimes try new workout classes but don’t feel pressured to keep it up.", "addiction_type": "none", "confidence": 0.30},
    {"id": 341, "text": "I enjoy volunteering but can take breaks without feeling guilty.", "addiction_type": "none", "confidence": 0.29},
    {"id": 342, "text": "I occasionally indulge in self-care activities but don't feel the need to do them often.", "addiction_type": "none", "confidence": 0.30},
    {"id": 343, "text": "I like to spend time outdoors but can also enjoy indoor activities.", "addiction_type": "none", "confidence": 0.35},
    {"id": 344, "text": "I need coffee to start my day, otherwise I feel sluggish.", "addiction_type": "substance_abuse", "confidence": 0.85},
    {"id": 345, "text": "I occasionally enjoy a glass of wine but don't rely on it.", "addiction_type": "none", "confidence": 0.40},
    {"id": 346, "text": "I have to check my phone constantly for messages and updates.", "addiction_type": "digital_addiction", "confidence": 0.82},
    {"id": 347, "text": "I play video games on weekends, but it's not something I have to do.", "addiction_type": "none", "confidence": 0.35},
    {"id": 348, "text": "I find myself needing to shop online frequently.", "addiction_type": "shopping_addiction", "confidence": 0.78},
    {"id": 349, "text": "I enjoy hiking occasionally but don’t feel compelled to go all the time.", "addiction_type": "none", "confidence": 0.30},
    {"id": 350, "text": "I often binge-watch series and struggle to stop.", "addiction_type": "digital_addiction", "confidence": 0.90},
    {"id": 351, "text": "I have a habit of reading novels, but I can easily put them down.", "addiction_type": "none", "confidence": 0.28},
    {"id": 352, "text": "I need to have my phone by my side at all times.", "addiction_type": "digital_addiction", "confidence": 0.87},
    {"id": 353, "text": "I enjoy spending time with friends but don’t feel pressured to socialize often.", "addiction_type": "none", "confidence": 0.30},
    {"id": 354, "text": "I find it hard to resist desserts when they're around.", "addiction_type": "food_addiction", "confidence": 0.76},
    {"id": 355, "text": "I like to experiment with cooking but can easily skip it.", "addiction_type": "none", "confidence": 0.32},
    {"id": 356, "text": "I often scroll through social media for hours without realizing it.", "addiction_type": "digital_addiction", "confidence": 0.80},
    {"id": 357, "text": "I enjoy doing puzzles occasionally but don’t feel the need to do them all the time.", "addiction_type": "none", "confidence": 0.29},
    {"id": 358, "text": "I sometimes feel compelled to check my email repeatedly.", "addiction_type": "digital_addiction", "confidence": 0.75},
    {"id": 359, "text": "I go for runs regularly but can also skip days without feeling guilty.", "addiction_type": "none", "confidence": 0.31},
    {"id": 360, "text": "I need to buy new clothes often, even when I don’t need them.", "addiction_type": "shopping_addiction", "confidence": 0.79},
    {"id": 361, "text": "I enjoy crafting on the weekends but don't have to do it all the time.", "addiction_type": "none", "confidence": 0.30},
    {"id": 362, "text": "I find myself needing to smoke cigarettes regularly.", "addiction_type": "substance_abuse", "confidence": 0.85},
    {"id": 363, "text": "I like to go for coffee with friends occasionally, but it’s not a must.", "addiction_type": "none", "confidence": 0.33},
    {"id": 364, "text": "I need to keep snacks handy to feel satisfied throughout the day.", "addiction_type": "food_addiction", "confidence": 0.74},
    {"id": 365, "text": "I enjoy attending concerts but can live without them.", "addiction_type": "none", "confidence": 0.30},
    {"id": 366, "text": "I often find myself needing to refresh my social media feed.", "addiction_type": "digital_addiction", "confidence": 0.82},
    {"id": 367, "text": "I love going out to eat but don’t do it regularly.", "addiction_type": "none", "confidence": 0.28},
    {"id": 368, "text": "I need to check my notifications every few minutes.", "addiction_type": "digital_addiction", "confidence": 0.88},
    {"id": 369, "text": "I like to try different restaurants but can cook at home instead.", "addiction_type": "none", "confidence": 0.31},
    {"id": 370, "text": "I often binge on snacks during late-night movie marathons.", "addiction_type": "food_addiction", "confidence": 0.77},
    {"id": 371, "text": "I find it difficult to put down a good book once I start.", "addiction_type": "none", "confidence": 0.34},
    {"id": 372, "text": "I need to have my favorite coffee brand every morning.", "addiction_type": "substance_abuse", "confidence": 0.83},
    {"id": 373, "text": "I enjoy gardening but don’t spend all my time on it.", "addiction_type": "none", "confidence": 0.32},
    {"id": 374, "text": "I feel compelled to check the latest news updates regularly.", "addiction_type": "digital_addiction", "confidence": 0.76},
    {"id": 375, "text": "I like to go out for walks, but it's not a necessity.", "addiction_type": "none", "confidence": 0.30},
    {"id": 376, "text": "I need to buy new gadgets frequently, even when my old ones work fine.", "addiction_type": "shopping_addiction", "confidence": 0.81},
    {"id": 377, "text": "I enjoy sketching occasionally but can go weeks without doing it.", "addiction_type": "none", "confidence": 0.29},
    {"id": 378, "text": "I often binge-watch shows late into the night.", "addiction_type": "digital_addiction", "confidence": 0.89},
    {"id": 379, "text": "I enjoy a casual drink with friends but don’t rely on it for fun.", "addiction_type": "none", "confidence": 0.30},
    {"id": 380, "text": "I have a habit of collecting shoes, even when I don't wear them all.", "addiction_type": "shopping_addiction", "confidence": 0.75},
    {"id": 381, "text": "I sometimes indulge in ice cream but don’t need it to feel satisfied.", "addiction_type": "food_addiction", "confidence": 0.32},
    {"id": 382, "text": "I like to travel but can also enjoy staying home.", "addiction_type": "none", "confidence": 0.31},
    {"id": 383, "text": "I often need to scroll through my phone while watching TV.", "addiction_type": "digital_addiction", "confidence": 0.84},
    {"id": 384, "text": "I occasionally buy new books but can borrow from the library.", "addiction_type": "none", "confidence": 0.30},
    {"id": 385, "text": "I find myself needing to smoke weed to relax after a long day.", "addiction_type": "substance_abuse", "confidence": 0.82},
    {"id": 386, "text": "I enjoy painting on weekends, but I can skip it without feeling bad.", "addiction_type": "none", "confidence": 0.30},
    {"id": 387, "text": "I have a tendency to play mobile games for hours without realizing it.", "addiction_type": "digital_addiction", "confidence": 0.79},
    {"id": 388, "text": "I like to try out new recipes but don’t feel compelled to cook every day.", "addiction_type": "none", "confidence": 0.32},
    {"id": 389, "text": "I often need to have energy drinks to stay awake during the day.", "addiction_type": "substance_abuse", "confidence": 0.85},
    {"id": 390, "text": "I occasionally buy new tech gadgets, but I don't feel the need to have the latest one.", "addiction_type": "none", "confidence": 0.34},
    {"id": 391, "text": "I struggle to resist shopping online during sales events.", "addiction_type": "shopping_addiction", "confidence": 0.78},
    {"id": 392, "text": "I enjoy visiting art galleries but don't need to do it often.", "addiction_type": "none", "confidence": 0.30},
    {"id": 393, "text": "I frequently feel the need to check my social media accounts throughout the day.", "addiction_type": "digital_addiction", "confidence": 0.81},
    {"id": 394, "text": "I occasionally binge on popcorn while watching movies at home.", "addiction_type": "food_addiction", "confidence": 0.73},
    {"id": 395, "text": "I like to go cycling but can skip it for weeks without issue.", "addiction_type": "none", "confidence": 0.31},
    {"id": 396, "text": "I find myself needing to drink soda throughout the day to stay energized.", "addiction_type": "substance_abuse", "confidence": 0.79},
    {"id": 397, "text": "I enjoy volunteering at the animal shelter but don't do it regularly.", "addiction_type": "none", "confidence": 0.30},
    {"id": 398, "text": "I can't help but scroll through fashion websites for new outfits.", "addiction_type": "shopping_addiction", "confidence": 0.76},
    {"id": 399, "text": "I enjoy meditation but can go days without practicing.", "addiction_type": "none", "confidence": 0.29},
    {"id": 400, "text": "I need to take naps during the day to function properly.", "addiction_type": "none", "confidence": 0.30}
]


# Convert data to a DataFrame
df = pd.DataFrame(data)

# Define a function for keyword-based addiction prediction
def predict_addiction(text):
    text_lower = text.lower()
    if any(keyword in text_lower for keyword in ["drink", "alcohol", "smoke", "substance", "cigarette", "weed", "drugs", "coffee", "tea"]):
        return "Substance Abuse"
    elif any(keyword in text_lower for keyword in ["gamble", "bet", "casino", "poker", "lottery"]):
        return "Gambling"
    elif any(keyword in text_lower for keyword in ["social media", "phone", "scroll", "online", "gaming", "video game", "tiktok", "facebook", "instagram"]):
        return "Digital Addiction"
    elif any(keyword in text_lower for keyword in ["food", "snack", "eat", "dessert", "binge eat", "sweets", "chocolate"]):
        return "Food Addiction"
    elif any(keyword in text_lower for keyword in ["shop", "buy", "shopping", "online store", "sale", "gadget"]):
        return "Shopping Addiction"
    else:
        return "Unknown"


# Streamlit app
st.title("Addiction Detection Predictor")
st.markdown("Enter a description of your behavior, and the app will predict the addiction type.")

# User input
user_input = st.text_area("Describe your behavior or concern:", placeholder="E.g., I keep checking my phone every few minutes and can't stop.")

if st.button("Predict"):
    if user_input.strip():
        prediction = predict_addiction(user_input)
        st.subheader("Prediction:")
        st.write(f"The predicted addiction type is: **{prediction}**")
    else:
        st.warning("Please enter some text to predict.")

# Optionally display sample data for reference
st.sidebar.header("Sample Data")
st.sidebar.dataframe(df)
